support for botd zoo
fingerprintjs/broyster pull request #47
Opened 2023-04-23 15:06 UTC by xnerhu

This pull request introduces changes necessary to support broyster in botd zoo. Mainly exposing some APIs and refactoring parts to take values explicitly instead of taking them from e.g. env file.

2023-04-30 12:17 UTC, Finesse requested changes

2023-04-30 12:17 UTC, Finesse commented on node/src/browserstack_session_factory.ts
👍

2023-04-30 12:29 UTC, Finesse commented
> Mainly exposing some APIs and refactoring parts to take values explicitly instead of taking them from e.g. env file.

Could you please work with @fpkamp to ensure that no class or function reads the credentials from the environment variables (gets them from the arguments instead)? For Karma, please create a separate function that only reads the credentials from the environment variables, and add this function to [the dependency collection](https://github.com/fingerprintjs/broyster/blob/6e42e19d1230c0c9fd2a56a9abe8a89b8e7afed9/node/src/karma_plugin.ts#L10).

2023-05-02 10:14 UTC, xnerhu commented
> > Mainly exposing some APIs and refactoring parts to take values explicitly instead of taking them from e.g. env file.
> 
> Could you please work with @fpkamp to ensure that no class or function reads the credentials from the environment variables (gets them from the arguments instead)? For Karma, please create a separate function that only reads the credentials from the environment variables, and add this function to [the dependency collection](https://github.com/fingerprintjs/broyster/blob/6e42e19d1230c0c9fd2a56a9abe8a89b8e7afed9/node/src/karma_plugin.ts#L10).

The previous implementation of `BrowserStackSessionFactory` loaded username and access token from `.env` file. In this PR I delegated store authentication data in `CapabilitiesFactory` which is passed to `BrowserStackSessionFactory`, but `CapFactory` and `BrowserStackSessionFactory` themselves don't load any env variables.

Regarding dependency collection, `makeBrowserStackSessionFactor` is already added. I think I shouldn't add `makeCapabilitiesFactory`

@Finesse

2023-05-04 04:15 UTC, Finesse commented
> The previous implementation of `BrowserStackSessionFactory` loaded username and access token from `.env` file. In this PR I delegated store authentication data in `CapabilitiesFactory` which is passed to `BrowserStackSessionFactory`, but `CapFactory` and `BrowserStackSessionFactory` themselves don't load any env variables.
> 
> Regarding dependency collection, `makeBrowserStackSessionFactor` is already added. I think I shouldn't add `makeCapabilitiesFactory`

@xnerhu You made `makeBrowserStackSessionFactor` read the credentials from environment variables (they don't necessarily come from an `.env` file). I meant creating a separate Karma dependency for the credentials to fix the problem that you want to solve in all classes and functions. It is not your scope, I'll do it, never mind.

2023-05-04 04:17 UTC, Finesse commented on example_project/.env.example
> +BROWSERSTACK_ACCESS_KEY=
@xnerhu In our team, the person who resolves a conversation is the person who starts the conversation. It is to ensure that the notice is really solved.

2023-05-04 04:18 UTC, Finesse commented on node/src/index_node.ts
> +export * from './capabilities_factory'
Please describe the new exports in the documentation.

2023-05-04 04:50 UTC, Finesse commented
@xnerhu What do you think about [these changes](https://github.com/fingerprintjs/broyster/pull/47/commits/b67f03edc29487cceee9dc90865ff9f80a4f663e)?

2023-05-04 10:54 UTC, fpkamp commented
Looks good, @Finesse should we wait for the documentation?

2023-05-05 03:28 UTC, Finesse commented
> Looks good, @Finesse should we wait for the documentation?

@fpkamp Yes. If you'd like, feel free to add the documentation.

2023-05-05 09:40 UTC, xnerhu reviewed
Looks good

2023-05-05 10:46 UTC, fpkamp commented on node/readme.md
> +    -   `CapabilitiesFactory` Stores credentials for BrowserStack
The caps factory actually creates an object that describes the parameters of the driver session that will be requested

2023-05-05 10:52 UTC, Finesse requested changes

2023-05-05 10:52 UTC, Finesse commented on node/readme.md
> +const capabilitiesFactory = new CapabilitiesFactory({ username, password }, local)
A parameter name is incorrect: `{ username, accessKey }`

2023-05-05 14:06 UTC, Finesse approved these changes

2023-05-05 14:07 UTC, merged